
rar_file: 'http://vcl.ucsd.edu/hed/HED-BSDS.tar'
download_path: '/Users/csrproject/edge/holy-edge/hed/data'
save_dir: /Users/csrproject/edge/holy-edge/hed
test_output: /Users/csrproject/edge/holy-edge/hed/test_out
model_weights_path: vgg16.npy
batch_size_train: 10
batch_size_val: 10
train_split: 0.8
max_iterations: 10000
optimizer: 'adam'
optimizer_params:
    learning_rate: 0.001
    weight_decay: 0.0002
loss_weights: 1.0
save_interval: 100
val_interval: 10
learning_rate_decay: 0.1
deep_supervision: True
target_regression: True
mean_pixel_value: [103.939, 116.779, 123.68]
channel_swap: [2, 1, 0]
training:
    dir: HED-BSDS
    list: HED-BSDS/train_pair.lst

    image_width: 480
    image_height: 480
    n_channels: 3

testing:
    dir: HED-BSDS
    list: HED-BSDS/test.lst

    image_width: 480
    image_height: 320
    n_channels: 3
test_snapshot: 5000
testing_threshold: 0.0
